### ISSUE TITLE
Did you ever finish this?

### ISSUE THREAD

**Issue by Taconut** [maraku/todoist-python-curses#1]
Just wondering. I was going to make my own todoist command line UI, but I figured if you finished it may as well piggyback off of your most recent version.

Thanks,

Alex Hulbert

**Comment by maraku** [comment]
Hey Alex,
I didn't finish this project as I switched over to task warrior. I'm now using taskwarrior on the command line and I run https://github.com/maraku/tasks which I can access from any web enabled device. If you are dedicated to using todoist, good luck! I hope that some of the code in this repo is useful for you.

**Comment by Taconut** [comment]
Thanks for the quick reply! I didn't think you'd respond so quickly to a GitHub comment, so I sent you an email, which you can ignore now. It looks like there's a script that syncs taskwarrior with Todoist. Since Taskwarrior is command line already, that solves my issue.

Thanks!
